* ldo_boost.tpl -- PROTOTYPE slew boost for eout, as a substitutable fragment.
*
* Not a schematic yet, deliberately: the sizing is unknown, and a netlist fragment sweeps
* in 40 seconds where a schematic edit does not. It moves into xschem only once a sizing
* passes transient, PVT phase margin, quiescent current and startup together.
*
* WHY THIS SHAPE. tb_ldo_slewtest establishes that the load-release cliff is a dI/dt
* threshold set by how fast eout can rise, and tb_ldo_m6sweep establishes that the obvious
* answer -- more current in XM6 -- cannot be used, because XM6 is the second stage's load
* device and its current is in the loop gain: 4u buys the 1 to 20 mA release and spends
* 7.1 deg of phase margin, putting nine of 243 corners under the 45 deg minimum.
*
* So the pull-up has to be LARGE DURING THE EVENT AND ABSENT FROM THE LOOP. This is the
* standard way to get that: XMpb is held off at the operating point, so it contributes no
* gm to the second stage, and is turned on only by the rising edge of vout itself.
*
*   vout rises -> XCb couples the edge onto nb -> XMnb conducts -> nx falls
*             -> XMpb turns on -> eout rises -> the pass device turns off
*
* Two properties fall out of the topology rather than the sizing, and both matter:
*
*   ONE-DIRECTIONAL. On a load APPLICATION vout falls, nb is driven below its bias, and
*   XMnb turns further off. The boost cannot make the droop worse, which is what makes it
*   safe to add to a block whose droop is already out of specification.
*
*   SELF-TERMINATING. nb decays back to its bias through XRb with a time constant of
*   XRb*XCb. The boost lasts as long as the edge does and then removes itself; there is no
*   state to reset and nothing to disable afterwards.
*
* ⚠️ nb is biased at the ibias node, NOT at vss. An hv nMOS with its gate at ground needs
* something like 0.7 V of kick before it conducts at all, which is most of the excursion
* being corrected -- the boost would arrive after the damage. The ibias node is the gate of
* XMr, a diode-connected hv nMOS carrying the 1 uA reference, so it sits at exactly the
* threshold of conduction for a device of the same type. Biasing nb there puts XMnb at the
* edge, where a small kick is enough. XRb draws no DC current: both ends sit at the same
* potential.
*
* ⛔ The static current XMnb then carries is the price, and it is set by its W/L against
* XMr's w=2u/l=1u. Sizing it larger than XMr multiplies the 1 uA reference directly into
* the quiescent budget, which has 24 uA of room against the published 35.8 uA.
*
* ⛔ STARTUP, AND WHY THE GATE IS NOT OPTIONAL. Measured against a no-boost control: the
* block's own startup is clean -- it settles at 1.20911 V with no overshoot at all, 9.4 us
* after enable. Add an ungated boost and startup breaks, because bringing the output up is
* a rising edge at vout and the boost cannot tell it from a load release. At Rb=1470u the
* output never reaches regulation at all (0.95 V peak); at Rb=300u it gets there but
* overshoots to 2.09 V. XMgt holds nb at vss until PGOOD asserts, which is precisely the
* "output is in regulation" condition, and PGOOD is already generated by x_pg.
*
* ⚠️ PGOOD deasserts during a large droop as well, so the boost is disabled for part of a
* load step. That is harmless HERE and the reason is timing, not principle: the release
* comes ~20 us after the step, long after PGOOD has reasserted. A load profile that
* released while still out of regulation would not be covered.
*
* ⛔ Rb IS NOT FREE TO SHRINK, which is counterintuitive: a shorter time constant attenuates
* slow edges more, so it looks like the way to stop the boost reacting to startup. It does
* the opposite on a load step. With a long Rb, nb is still BELOW its bias from the load
* application when the output recovers, so the recovery's rising edge only brings it back
* toward bias -- the boost stays off. Shorten Rb and nb has already decayed back, the
* recovery fires the boost, the boost turns the pass device off against the loop, and with
* an ideal current sink on 20 pF the output is dragged to -4.5 V. ngspice converges on that
* without a single warning, so it is a result and not an artifact.
*
* ⛔ WHERE THIS SIZING STANDS, from the 81-corner transient sweep (boost_pvt.sh). It does
* the job it was built for: NO corner reaches the rail, against 81 of 81 near it without
* the boost, and the worst overshoot is 582 mV at ss/res_bcs/110 C/3.0 V. The 243-corner
* AC sweep is 46.04 deg minimum against the block's own 45.62, none below 45.
*
* ⛔ But FIVE of the 81 drive the output NEGATIVE during the load step, and they are not
* scattered -- every one is at 110 C with res_bcs, across ss, tt and ff. Both factors push
* the same way: 110 C lowers XMnb's threshold so the boost is more easily triggered, and
* res_bcs is the LOWEST sheet, 1020 against 1360 ohm/sq typical, which shortens XRb's time
* constant by a quarter. That is the short-Rb failure already characterised above, reached
* by the corner instead of by the drawn value -- the boost fires on the output's own
* RECOVERY from the droop and fights the loop.
*
* 🔑 SO THE TOPOLOGY IS THE LIMIT, NOT THE SIZING. A dv/dt sensor cannot distinguish an
* output rising because the load was released from an output rising because the loop is
* correcting a droop; both are rising edges at vout. Making it fire only when the output is
* ABOVE its regulation point needs the ERROR, not the slew -- vfb against vref rather than
* a high-pass on vout. Sizing this one further is fitting a boundary that the corners move.
*
* Substituted and verified by sim/boost.sh.
* --------------------------------------------------------------------------------------
XCb  vout nb    cap_cmomf w=@CB@ l=@CB@ mmin=1 mmax=4 subblock=0 m=1 mm_ok=1
XRb  nb   ibias sub! rhigh w=1u l=@RB@ m=1 b=0 mm_ok=1
XMnb nx   nb    vss vss sg13_hv_nmos w=@WNB@ l=@LNB@ ng=1 m=1 mm_ok=1
XRnx vin  nx    sub! rhigh w=1u l=@RNX@ m=1 b=0 mm_ok=1
XMpb eout nx    vin vin sg13_hv_pmos w=@WPB@ l=0.5u ng=1 m=1 mm_ok=1
* Startup gate: XMgt clamps nb to vss while PGOOD is low.
*
* ⛔ BOTH PLACEMENTS OF THIS GATE COST SOMETHING, AND XCb IS WHY. Clamping nb drags it from
* its 0.68 V bias to ground when PGOOD deasserts during a load step, and XCb couples that
* step onto vout: 1 pF against 20 pF of XCout, measured as droop going from 338 mV to
* 428 mV. Moving the gate into XMnb's source instead leaves nb undisturbed and recovers the
* droop exactly -- but then XCb couples the STARTUP ramp through XRb into the shared ibias
* node, which biases the whole amplifier, and the output starts up to 3.0 V. The clamp was
* shunting that charge to ground, which is why it had clean startup.
*
* So the gate placement is not the free variable. XCb is: it is a capacitive DIVIDER against
* XMnb's gate capacitance, not a charge pump, so it only has to be large against a few tens
* of fF. Sizing it down shrinks every injection above in proportion -- and the area with it.
Xinv_pg pgood_n pgood vddd vss sg13cmos5l_inv_1
XMgt nb pgood_n vss vss sg13_lv_nmos w=@WGT@ l=0.13u ng=1 m=1 mm_ok=1
