* PVT corner instance -- generated by run_pvt.sh, do not edit directly.
.lib @M@/cornerMOShv.lib @MOS@
.lib @M@/cornerMOSlv.lib @MOS@
.include @M@/cap_mfringe.lib
.lib @M@/cornerRES.lib @RES@
.include ldo_cells.spice
.temp @TEMP@
Vin vin 0 @VIN@
Vrefbg vref_bg 0 1.2
Vss vss 0 0
Ibias 0 ibias DC 10u
Iload vout 0 DC 0
Vt0 vtrim0 0 0
Vt1 vtrim1 0 0
Vt2 vtrim2 0 0
Vt3 vtrim3 0 0
Vt4 vtrim4 0 1.2
x_vref vref_bg vref vss ldo_vref
x_amp  vref vfb ibias eout vin vss ldo_erramp
x_pass eout vout vin ldo_pass
x_fb   vtrim0 vtrim1 vtrim2 vtrim3 vtrim4 vfbd vout vss ldo_fbtrim
Lbrk vfbd vfb 1T
Vinj vfbd vfb AC 1
XMpre vout ibias vss vss sg13_hv_nmos w=2u l=1u
XCc   eout vout cap_mfringe w=30u l=30u mmin=1 mmax=4
XCout vout vss  cap_mfringe w=93u l=93u mmin=1 mmax=4
.control
  op
  print v(vout)
  print -i(Vin)
  ac dec 40 1 1G
  let T = -v(vfbd)/v(vfb)
  let tdb = db(T)
  let tph = 180/pi*cph(T)
  wrdata pvt/@TAG@.csv tdb tph
.endc
.end
