* PVT corner instance -- generated by run_pvt.sh, do not edit directly.
.lib @M@/cornerMOShv.lib @MOS@
.lib @M@/cornerMOSlv.lib @MOS@
.include @M@/cap_mfringe.lib
.lib @M@/cornerRES.lib @RES@
* The resistor model's body terminal is the global substrate node `sub!`. Unless it is
* declared global AND tied, it floats inside each subcircuit, the matrix is singular, and
* ngspice quietly abandons its DC strategies and falls back to a transient operating
* point -- which returns numbers that look plausible and are not solutions. Declare and
* tie it in every bench.
* ldo_enable instantiates a standard-cell inverter for the 1.2 V control-bus side.
.include /foss/pdks/ihp-sg13cmos5l/libs.ref/sg13cmos5l_stdcell/spice/sg13cmos5l_stdcell.spice
.global sub!
.include ldo_cells.spice
.temp @TEMP@
Vin vin 0 @VIN@
Vrefbg vref_bg 0 1.2
Vss vss 0 0
Vddd vddd 0 1.2
Ven  en   0 1.2
Vilim ilim_en 0 1.2
Vsub sub! 0 0
Ibias 0 ibias DC 1u   $ harness supplies 1 uA (ibias1u_*); multiplied 10x on-slot
Iload vout 0 DC 0
Vt0 vtrim0 0 0
Vt1 vtrim1 0 0
Vt2 vtrim2 0 0
Vt3 vtrim3 0 0
Vt4 vtrim4 0 1.2
* Blocks instantiated by hand so the feedback node can be broken. Port order MUST track
* the cells -- this bench silently stopped elaborating when ldo_vref, ldo_erramp and
* ldo_enable gained ports, and ngspice then reported "too few parameters" and produced no
* output at all, leaving stale CSVs on disk to be read as if they were results.
x_vref vref_bg vref vss vref_pg ldo_vref
x_amp  vref vfb ibias en_n eout vin vss ldo_erramp
x_pass eout vout vin ldo_pass
x_fb   vtrim0 vtrim1 vtrim2 vtrim3 vtrim4 vfbd vout vss ldo_fbtrim
x_en   en ibias eout en_n vin vddd vss ldo_enable
x_pg   vfb vref_pg ibias pgood vddd vss ldo_pgood
x_il   ibias ilim_en vout eout oc vin vddd vss ldo_ilim
* DC-0 / AC-1 source alone: short at DC so the operating point is the real
* closed-loop one, 1 V injection at AC. No parallel inductor -- two zero-impedance
* elements on one node pair is a degenerate loop for the DC solve.
Vinj vfbd vfb DC 0 AC 1
XMpre vout ibias vss vss sg13_hv_nmos w=20u l=1u ng=1 m=1
XCc   eout vout cap_mfringe w=30u l=30u mmin=1 mmax=4
XCout vout vss  cap_mfringe w=93u l=93u mmin=1 mmax=4
.control
  op
  print v(vout)
  print -i(Vin)
  ac dec 40 1 1G
  let T = -v(vfbd)/v(vfb)
  let tdb = db(T)
  let tph = 180/pi*cph(T)
  wrdata pvt/@TAG@.csv tdb tph
.endc
.end
